language: php

php:
    - 5.6	
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
 - SYMFONY_VERSION=3.4.*
 - SYMFONY_VERSION=4.0.*

branches:
    only:
        - master
        - update-to-3-4
        - /^\d+\.\d+$/

#symfony 3.0 is no longer supported by symfony, allow it to fail
matrix:
    allow_failures:
        - php: nightly

before_script:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
    - composer update --prefer-dist

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# Run coveralls ONLY if under php native, and NOT hhvm
after_success: |
 sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;'

#notifications:
#    email: julienguyon@hotmail.com
